// Generated by CU compiler
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// CU Standard Library - Portable utilities
#include "cu_std.h"


typedef struct {
    uint64_t pointer_size;
    uint64_t pointer_align;
    bool is_little_endian;
    bool is_big_endian;
    const char* platform_name;
    const char* arch_name;
} PlatformInfo;




















int32_t main(void) {
    printf("--- CU STD Comprehensive Test ---\n\n");
    PlatformInfo info = cu_get_platform_info();
    printf("[Platform]\n");
    printf("  OS:           %s\n", info.platform_name);
    printf("  Arch:         %s\n", info.arch_name);
    printf("  Ptr Size:     %llu bytes\n", info.pointer_size);
    printf("  Ptr Align:    %llu bytes\n", info.pointer_align);
    printf("  Endianness:   %s\n", (info.is_little_endian ? "Little" : "Big"));
    printf("\n[Endianness]\n");
    uint32_t val = 3735928559;
    printf("  Original:     0x%08X\n", val);
    printf("  Swap32:       0x%08X\n", cu_bswap32(val));
    printf("  As BigEnd:    0x%08X\n", cu_be32(val));
    printf("  As LitEnd:    0x%08X\n", cu_le32(val));
    printf("\n[Strings]\n");
    char buffer[32];
    cu_memset(buffer, 0, 32);
    cu_strcpy(buffer, "Hello");
    printf("  After cpy:    '%s'\n", buffer);
    cu_strcat(buffer, ", World!");
    printf("  After cat:    '%s'\n", buffer);
    uint64_t len = cu_strlen(buffer);
    printf("  Length:       %llu\n", len);
    int32_t cmp = cu_strcmp(buffer, "Hello, World!");
    printf("  Cmp (equal):  %d\n", cmp);
    (cmp = cu_strcmp(buffer, "Different"));
    printf("  Cmp (diff):   %d\n", cmp);
    printf("\n[Memory]\n");
    int32_t arr1[5] = {1, 2, 3, 4, 5};
    int32_t arr2[5];
    cu_memcpy(arr2, arr1, (sizeof(int32_t) * 5));
    int32_t mem_diff = cu_memcmp(arr1, arr2, (sizeof(int32_t) * 5));
    printf("  MemCmp(eq):   %d\n", mem_diff);
    (arr2[2] = 99);
    (mem_diff = cu_memcmp(arr1, arr2, (sizeof(int32_t) * 5)));
    printf("  MemCmp(diff): %d\n", mem_diff);
    printf("\n[Math & Bits]\n");
    int32_t neg = (-42);
    printf("  Abs(-42):     %d\n", cu_abs_i32(neg));
    printf("  Max(10, 20):  %d\n", cu_max_i32(10, 20));
    printf("  Min(10, 20):  %d\n", cu_min_i32(10, 20));
    uint32_t bits = 4026531841;
    printf("  Value:        0x%08X\n", bits);
    printf("  Popcount:     %u\n", cu_popcount32(bits));
    printf("  CLZ (lead 0): %u\n", cu_clz32(bits));
    printf("  CTZ (trail 0):%u\n", cu_ctz32(bits));
    uint32_t bits2 = 8;
    printf("  Value2:       0x%08X\n", bits2);
    printf("  CTZ2:         %u\n", cu_ctz32(bits2));
    return 0;
}

