// Generated by CU compiler
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// CU Standard Library - Portable utilities
#include "cu_std.h"


int32_t main(void) {
    printf("--- Control Flow Test ---\n");
    for (int32_t i = 0; (i < 4); (i++)) {
        switch (i)         {
        case 0:
            printf("Case 0\n");
            break;
        case 1:
            printf("Case 1\n");
            break;
        case 2:
            {
                printf("Case 2 (Block)\n");
                break;
            }
        default:
            printf("Default (i = %d)\n", i);
            break;
        }
    }
    printf("\n--- Do-While Test ---\n");
    int32_t count = 0;
    do     {
        printf("Count: %d\n", count);
        (count++);
    }
    while ((count < 3));
    printf("\n--- Inline ASM Test ---\n");
    int32_t val = 10;
    int32_t result = 0;
    __asm__("add %w0, %w1, #5" : "=r" ( result ) : "r" ( val ) );
    printf("ASM result (10 + 5): %d\n", result);
    return 0;
}

