// Generated by CU compiler
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// CU Standard Library - Portable utilities
#include "cu_std.h"




typedef struct {
    int32_t x;
    int32_t y;
} Point;

Point Point_new(int32_t x, int32_t y) {
    Point p;
    (p.x = x);
    (p.y = y);
    return p;
}

int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t main(void) {
    int32_t result = add(5, 3);
    printf("5 + 3 = %d\n", result);
    Point p = Point_new(10, 20);
    printf("Point: (%d, %d)\n", p.x, p.y);
    int32_t* mem = ((int32_t*)malloc(sizeof(int32_t)));
    if ((mem != NULL)) {
        ((*({ CU_CHECK_NULL(mem, "examples/hello.cup", 1); mem; })) = 42);
        printf("Allocated value: %d\n", (*({ CU_CHECK_NULL(mem, "examples/hello.cup", 1); mem; })));
        free(mem);
    }
    return 0;
}

