// Generated by CU compiler
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern int32_t printf(int8_t* fmt, ...);

extern void* malloc(uint64_t size);

extern void free(void* p);

typedef struct {
    int32_t x;
    int32_t y;
} Point;

Point Point_new(int32_t x, int32_t y) {
    Point p;
    (p.x = x);
    (p.y = y);
    return p;
}

int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t main(void) {
    int32_t result = add(5, 3);
    printf("5 + 3 = %d\n", result);
    Point p = Point_new(10, 20);
    printf("Point: (%d, %d)\n", p.x, p.y);
    int32_t* mem = ((int32_t*)malloc(sizeof(int32_t)));
    if ((mem != NULL)) {
        ((*mem) = 42);
        printf("Allocated value: %d\n", (*mem));
        free(mem);
    }
    return 0;
}

