// Generated by CU compiler
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// CU Standard Library - Portable utilities
#include "cu_std.h"









void test_endianness(void) {
    uint32_t value = 305419896;
    printf("Original value: 0x%08X\n", value);
    printf("Big endian:     0x%08X\n", cu_be32(value));
    printf("Little endian:  0x%08X\n", cu_le32(value));
}

void test_memory(void) {
    char buffer[20];
    char* source = "Hello, CU!";
    cu_memcpy(buffer, source, (cu_strlen(source) + 1));
    printf("Copied string: %s\n", buffer);
    printf("String length: %llu\n", cu_strlen(buffer));
}

void test_alignment(void) {
    int32_t aligned_array[4];
    void* p = aligned_array;
    printf("Pointer: %p\n", p);
    printf("Aligned to 4?  %d\n", cu_is_aligned(p, 4));
    printf("Aligned to 8?  %d\n", cu_is_aligned(p, 8));
    printf("Aligned to 16? %d\n", cu_is_aligned(p, 16));
}

void test_bits(void) {
    uint32_t value = 181;
    printf("Value: 0x%08X (binary: 0b10110101)\n", value);
    printf("Population count (set bits): %u\n", cu_popcount32(value));
}

int32_t main(void) {
    printf("=== CU Standard Library Demo ===\n\n");
    printf("--- Endianness Test ---\n");
    test_endianness();
    printf("\n--- Memory Operations Test ---\n");
    test_memory();
    printf("\n--- Alignment Test ---\n");
    test_alignment();
    printf("\n--- Bit Manipulation Test ---\n");
    test_bits();
    return 0;
}

